# Generated by Django 4.2 on 2025-08-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedOriginCORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(verbose_name='Origen permitido')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración CORS',
                'verbose_name_plural': 'Configuraciones CORS',
            },
        ),
        migrations.CreateModel(
            name='SupportEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de envío')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('from_email', models.CharField(max_length=100, verbose_name='Nombre remitente')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correo',
            },
        ),
    ]
