# Generated by Django 4.2 on 2025-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportemailconfig',
            name='host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='supportemailconfig',
            name='port',
            field=models.IntegerField(default=587, verbose_name='Puerto'),
        ),
        migrations.AddField(
            model_name='supportemailconfig',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS'),
        ),
        migrations.AlterField(
            model_name='supportemailconfig',
            name='from_email',
            field=models.CharField(max_length=100, verbose_name='Remitente'),
        ),
    ]
