# Generated by Django 4.2 on 2025-08-17 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMoodle', models.CharField(max_length=12, verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Usuario Moodle',
                'verbose_name_plural': 'Usuarios Moodle',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Consulta / Requerimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('override_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo alternativo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('answered', 'Respondida'), ('closed', 'Cerrada')], default='pending', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='appsoporte.costumer')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='RolCostumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30, unique=True, verbose_name='Rol en Moodle')),
            ],
            options={
                'verbose_name_plural': 'Roles en Moodle',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_ok', models.BooleanField(default=False, verbose_name='Envío exitoso')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Error de envío')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='appsoporte.question')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AddField(
            model_name='costumer',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsoporte.rolcostumer'),
        ),
    ]
