# Generated by Django 4.2 on 2025-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMoodle', models.CharField(max_length=12, verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Usuario Moodle',
                'verbose_name_plural': 'Usuarios Moodle',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Consulta / Requerimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('override_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo alternativo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('answered', 'Respondida'), ('closed', 'Cerrada')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_ok', models.BooleanField(default=False, verbose_name='Envío exitoso')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Error de envío')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='RolCostumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30, unique=True, verbose_name='Rol en Moodle')),
            ],
            options={
                'verbose_name_plural': 'Roles en Moodle',
            },
        ),
    ]
