# Generated by Django 4.2 on 2025-08-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsoporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='appsoporte.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='appsoporte.costumer'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsoporte.rolcostumer'),
        ),
    ]
