# Generated by Django 4.2 on 2025-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
