# Generated by Django 4.2 on 2025-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user_input', models.TextField(verbose_name='Consulta')),
                ('predicted_tag', models.CharField(max_length=100, verbose_name='Predicción')),
                ('confidence', models.FloatField(verbose_name='Confianza')),
                ('related_tags', models.TextField(help_text='Lista separada por comas', verbose_name='Relacionados')),
            ],
            options={
                'verbose_name': 'Consulta realizada',
                'verbose_name_plural': 'Consultas chatbot',
            },
        ),
    ]
