# Generated by Django 4.2 on 2025-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.TextField()),
                ('predicted_tag', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('related_tags', models.TextField(help_text='Lista separada por comas')),
            ],
        ),
    ]
