# Generated by Django 4.2 on 2025-08-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsoporte', '0001_initial'),
        ('appchatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultachatbot',
            options={'verbose_name': 'Consulta realizada', 'verbose_name_plural': 'Consultas chatbot'},
        ),
        migrations.AddField(
            model_name='consultachatbot',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='appsoporte.costumer', verbose_name='Usuario Moodle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultachatbot',
            name='confidence',
            field=models.FloatField(verbose_name='Confianza'),
        ),
        migrations.AlterField(
            model_name='consultachatbot',
            name='predicted_tag',
            field=models.CharField(max_length=100, verbose_name='Predicción'),
        ),
        migrations.AlterField(
            model_name='consultachatbot',
            name='related_tags',
            field=models.TextField(help_text='Lista separada por comas', verbose_name='Relacionados'),
        ),
        migrations.AlterField(
            model_name='consultachatbot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='consultachatbot',
            name='user_input',
            field=models.TextField(verbose_name='Consulta'),
        ),
    ]
