# Generated by Django 4.2 on 2025-08-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appchatbot', '0001_initial'),
        ('appsoporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultachatbot',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='appsoporte.costumer', verbose_name='Usuario Moodle'),
        ),
    ]
