# Generated by Django 4.2 on 2025-05-27 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('user_moodle', models.CharField(default='Anónimo', max_length=50, null=True, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
